/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/cli.py:617: UserWarning: `System.configure_optimizers` will be overridden by `LightningCLI.configure_optimizers`.
  _warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Global seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------
100%|█████████████████████████████████████████████████████████████████████████████████| 139/139 [00:00<00:00, 174.38it/s]
100%|███████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 740.86it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
  | Name                 | Type                    | Params
-----------------------------------------------------------------
0 | model                | MixStyleTransferModel   | 26.0 M
1 | generate_mix_console | AdvancedMixConsole      | 0
2 | loss                 | MultiResolutionSTFTLoss | 0
3 | sisdr                | SISDRLoss               | 0
4 | mrstft               | MultiResolutionSTFTLoss | 0
-----------------------------------------------------------------
26.0 M    Trainable params
0         Non-trainable params
26.0 M    Total params
104.185   Total estimated model params size (MB)
Found 196 mix directories in ['/import/c4dm-datasets/MedleyDB_V1/V1', '/import/c4dm-datasets/MedleyDB_V2/V2'].
Found 139 mix directories in train set.
Found 101 mix directories with tracks less than 20 and more than 4.
Found 196 mix directories in ['/import/c4dm-datasets/MedleyDB_V1/V1', '/import/c4dm-datasets/MedleyDB_V2/V2'].
Found 30 mix directories in val set.
Found 20 mix directories with tracks less than 20 and more than 4.

Sanity Checking DataLoader 0:   0%|                                                                | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/homes/ssv02/Diff-MST/main.py", line 26, in <module>
    cli_main()
  File "/homes/ssv02/Diff-MST/main.py", line 15, in cli_main
    cli = LightningCLI(
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 353, in __init__
    self._run_subcommand(self.subcommand)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 642, in _run_subcommand
    fn(**fn_kwargs)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 976, in _run_stage
    self._run_sanity_check()
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run_sanity_check
    val_loop.run()
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 380, in _evaluation_step
    call._call_callback_hooks(trainer, hook_name, output, *step_kwargs.values())
  File "/homes/ssv02/Diff-MST/env/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
TypeError: LogAudioCallback.on_validation_batch_end() missing 1 required positional argument: 'dataloader_idx'